version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/mentat/terraform-provider-conjur
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -o /tmp/terraform-provider-conjur
      - store_artifacts:
          path: /tmp/terraform-provider-conjur
