version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/mentat/terraform-provider-conjur
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -o /tmp/terraform-provider-conjur
      - store_artifacts:
          path: /tmp/terraform-provider-conjur
  build-windows:
    executor:
      name: win/default 
      size: "medium"
    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: go build -o /tmp/terraform-provider-conjur-windows
        shell: bash.exe
      - store_artifacts:
          path: /tmp/terraform-provider-conjur-windows
